### ISSUE TITLE
Basic Story Intro

### ISSUE THREAD

**Issue by aire39** [AhmadAlkadi/RollingKnight#18]
Expand the story a bit

**Comment by ssmckevin** [comment]
// note these lines would be possibly placed in game using a textbox and stored in an array for output
// the user would click or space bar to progress through the story of the game

**Comment by ssmckevin** [comment]
-- Chapter 1 --

It was a quiet and tranquil night through out the kingdom. The King of Mice sleeps peacefully, embracing his cheese scented pillow. "Pepper jack. Cheddar. Blue. Oh cheese, what would I do without you." Faint whispering could be heard down the hallway underneath the King's chambers. There is quiet rumbling and the pitter-patter of footsteps. The group is hooded in dark green tunics which help conceal their identities. One of the men peeks out toward the entrance. "Two guards. Left and right." The mysterious figure nods and takes out a vial of liquid. It gleams and glows a subtle yet bright magenta. "Sweet dreams." The hooded figure throws her vial and it shatters against the ground, vaporizing into a gaseous substance. Before the guards can cry out for help, they succumb to the song of the spell and fall into a deep slumber. "There you have it now hurry. Only lasts for several of minutes, let's get this rolling." The rest of the group rush into position. One of the members places a charge of gunpowder and a drop of liquid from a vial. He places on his goggles and takes out a piece of flint and steel. "Incoming!" He strikes it and runs back with the rest of the members. The iron doors blow into pieces, sending chunks of metal everywhere. A minute later most of the group dart into the vault. "Scouts! How is our pathway?" The two turn toward their leader. "Madame practically everyone in the castle is asleep." She nods. "Jocks! Place "El Rey del Queso" onto the cart and let's go, go, go!" The group nods. The jocks gaze at the massive miracle of cheese into front of them and carry it onto their conveniently sized cart. As the rush out of the vault and eventually the castle, the scouts ahead of them toss their magenta vials against mice who were still awake. The rest rapidly trail behind the wake of sleeping mice, undetected. They all escape successfully and the night begins to fade.

**Comment by aire39** [comment]
add to the wiki page

**Comment by aire39** [comment]
This is complete
