### ISSUE TITLE
Tileset Implementation

### ISSUE THREAD

**Issue by tinyVaris** [AhmadAlkadi/RollingKnight#29]
Implementation of the tileset we are using for the game.

The asset we are using is called Cavernas by Adam Saltman.
https://adamatomic.itch.io/cavernas

**Comment by aire39** [comment]
stringstar fields by Trixie
https://trixelized.itch.io/starstring-fields

Cavernas by Adam Saltsman
https://adamatomic.itch.io/cavernas

We voted for Cavernas but we may use both
