### ISSUE TITLE
Add Chapter 2 Part of Story

### ISSUE THREAD

**Issue by aire39** [AhmadAlkadi/RollingKnight#31]
Add 2nd part of the story which involves the crows

**Comment by ssmckevin** [comment]
Chapter 2
The mouse lays on his bed dreaming about the finest chocolates. The smooth and melty texture flows through his mind. Not all mice like cheese. For little Winsworth chocolate was more of his taste.”Ahhhh! My cheese! Why!!!” The little mouse pounces out of his bed and gets into gear. He runs down to check the King’s commotion. As he runs he sees the King on the floor in defeat. A few of the guards stand by him in disappointment. “My great great great great grandmother had hand crafted this very cheese with her own life and soul.” The King points to the ground. Scattering of dark feathers coated the halls of the vault. “Winsworth. You are one of my greatest assets. You haven’t been a soldier for very long but we can all see your potential. Set forth toward the Crow Kingdom.” The King turns to face him. “Bring me back my family’s legacy.” Winsworth salutes. The guards bring him all the supplies and packs he needs to set out for adventure. “I would not send out any ordinary soldier. Within you lies a true power, blessing or a curse.” As the mouse prepares to set out, the King grabs his shoulder. “Do not worry you will also have your fair share of cheese and other riches provided by me. Well just a teeny bit.” The King laughs and everyone else stares at him in silence. He wacks his advisor next to him and he and the rest start laughing. “Okay then off you go Winsworth. Bring me the cheese and do not ever come back until you do.” The guards lead him away and the King laughs continuously until it fades out in the distance. Winsworth marches on forward out of the kingdom and toward the path of feathers. 

After a couple of miles, the morning shifts to noon and sounds of chirping can be heard in the distance. “Secure the area. Guard the pathway.” Winsworth hides near a brush as the Crow soldiers, Cronen, bicker amongst themselves. All of a sudden he fluctuates and transforms into a ball of yarn, making too much noise. “Over there! A blasted magic wielder, prepare yourselves!” One of the soldiers throws his magenta solution toward the bush. It cracks and shatters, unleashing gases of the same color into the air. Winsworth collapses and falls into a deep slumber. A mysterious warmth envelops the mouse’s mind. It was as though a warm blanket wrapped around him on a cold winter night. “Wake up.” The mouse struggles to move nor awaken. “Your powers are still awakening. Get up and go find the cheese they have taken away from your King. I will tell you what to do next.” The warmth starts to intensify. “Please I beg of you, a great reward I will bestow upon you. As an initial payment to what I can give you is this.” Winsworth awakens and bolts out of his restraints. The mouse looks around to see that he is in some hidden cavern alone. A ladder going upwards and feathers scattered about indicates that he is captured. His yarn form combusts into flames yet he does not feel any harm. He becomes a fire incarnate.

**Comment by aire39** [comment]
Added to story section of wiki. This is complete
